// Generated by @promethean-os/shadow-conf
import dotenv from "dotenv";

dotenv.config();

export const apps = 
[
  {
    "name": "app",
    "cwd": "./....windowssystem32"
  }
];

export const triggers = 
[];

export const schedules = 
[];

export const actions = 
[];
